//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoluDej.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Arrondissements
    {
        public Arrondissements()
        {
            this.Entreprises = new HashSet<Entreprises>();
            this.Restaurants = new HashSet<Restaurants>();
        }
    
        public int Id { get; set; }
        public int Ville { get; set; }
        public string Arrondissement { get; set; }
    
        public virtual Villes Villes { get; set; }
        public virtual ICollection<Entreprises> Entreprises { get; set; }
        public virtual ICollection<Restaurants> Restaurants { get; set; }
    }
}
