//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoluDej.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Entreprises
    {
        public Entreprises()
        {
            this.Utilisateurs = new HashSet<Utilisateurs>();
        }
    
        public int id { get; set; }
        public string nom { get; set; }
        public int arrondissement { get; set; }
        public int ville { get; set; }
    
        public virtual Arrondissements Arrondissements { get; set; }
        public virtual Villes Villes { get; set; }
        public virtual ICollection<Utilisateurs> Utilisateurs { get; set; }
    }
}
