//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoluDej.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Evenements
    {
        public int Id { get; set; }
        public int Restaurant { get; set; }
        public System.DateTime Date { get; set; }
        public bool PlacesLimitees { get; set; }
        public Nullable<int> NombrePlaces { get; set; }
        public string Commentaire { get; set; }
    
        public virtual Restaurants Restaurants { get; set; }
    }
}
