//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoluDej.Models
{
    using System.Collections.Generic;

    public partial class Restaurants
    {
        public Restaurants()
        {
            this.Evenements = new HashSet<Evenements>();
        }

        public int Id { get; set; }
        public string Nom { get; set; }
        public string Adresse { get; set; }
        public string SiteWeb { get; set; }
        public string Telephone { get; set; }
        public string Commentaire { get; set; }

        public virtual ICollection<Evenements> Evenements { get; set; }
    }
}
