//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoluDej.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Utilisateurs
    {
        public string nom { get; set; }
        public string prenom { get; set; }
        public string mailSolutec { get; set; }
        public string mailNotification { get; set; }
        public string motDePasse { get; set; }
        public System.DateTime dateDeNaissance { get; set; }
        public int idEntreprise { get; set; }
        public int id { get; set; }
    
        public virtual Entreprises Entreprises { get; set; }
    }
}
